sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tMY8MAPXd2TzMMXJx1M
    access-key-secret: G5p34PwZ8edwIi70rcVz0h2UARccBE
    bucket-name: itcast-sky-takeaway