sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tMY8MAPXd2TzMMXJx1M
    access-key-secret: G5p34PwZ8edwIi70rcVz0h2UARccBE
    bucket-name: itcast-sky-takeaway
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx5eea5f990916e210
    secret: febc8e9035fc42ceb90cdfff065e031d

    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://1006b5ad.r3.cpolar.cn/notify/paySuccess
    refundNotifyUrl: https://1006b5ad.r3.cpolar.cn/notify/refundSuccess