sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.162.129
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com

    bucket-name: itcast-sky-takeaway
  redis:
    host: 192.168.162.129
    port: 6379
    password: 123456
    database: 0
  wechat:


    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl:  https://6f0b7e43.r26.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://6f0b7e43.r26.cpolar.top/notify/refundSuccess